# Generated by Django 4.0 on 2022-12-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
