# Generated by Django 4.0 on 2023-01-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customer_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_wheel_available',
            field=models.BooleanField(default=True),
        ),
    ]
