# Generated by Django 4.0 on 2023-01-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customer_is_wheel_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_wheel_available',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_wheel_spin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
