# Generated by Django 4.0 on 2023-01-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customer_is_wheel_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_wheel_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_wheel_spin',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
