# Generated by Django 4.0 on 2022-12-26 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customer_name'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFortune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fortune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fortune')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
    ]
